name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.139.4' # Match the Hugo version you're using locally

    - name: Build Hugo project
      run: hugo --minify # Minify the output for production

    - name: List public directory
      run: ls -R ./public # Debugging step to verify the build output

    - name: Deploy to MrKnappsClass
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TO_MRKNAPPSCLASS }} # Use your PAT.
        publish_dir: ./public # Directory containing the built site
        external_repository: MrKnappsClass # Target repository
        publish_branch: main # Branch to deploy to